development:
  app_title: <%= ENV['HB_APP_TITLE'] || 'Home Banking' %>
test:
  app_title: <%= ENV['HB_APP_TITLE'] || 'Home Banking' %>
production:
  app_title: <%= ENV['HB_APP_TITLE'] || 'Home Banking' %>
